services:
  - type: web
    name: events-app
    env: node
    plan: free
    buildCommand: npm install && node scripts/build-production.mjs
    startCommand: node start-production.js
    healthCheckPath: /ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: HOST
        value: 0.0.0.0